---
title: "Comment Classification: Pretrained"

execute:
  enabled: false
---

# Introduction


<!-- describe general idea of what we are doing here -->



## Setting up the Virtual Environment

To install Python libraries, navigate to the folder "like_dislike" in your terminal, then run `python3 -m venv .venv` to create a new virtual environment and activate it using `source .venv/bin/activate`. Run `pip3 install -r requirements.txt` to install required Python libraries into the created virtual environment.


## Libraries
```{python}
import pandas as pd
import os
from transformers import pipeline, AutoTokenizer, AutoModelForSequenceClassification
import torch
from tqdm.auto import tqdm
```

## Hugging Face

Hugging Face provides an open-source platform that allows data scientists, computer scientists, and researchers to share models and datasets. We will use a model from its comprehensive transformer library. To do so:

1. Create an access token on [Hugging Face](https://huggingface.co/settings/tokens).

2. Run in terminal: `echo 'export HF_TOKEN="hf_yournewtoken"' >> ~/.zshrc && source ~/.zshrc`

3. Run to verify: `echo $HF_TOKEN`

```{python}
from huggingface_hub import login
login(token=os.environ["HF_TOKEN"])
```

Use `pipeline` "zero-shot-classification" to download the classifier model:

```{python}
# example, exchange
post_classifier = pipeline(
    "zero-shot-classification", 
    model="MoritzLaurer/xlm-v-base-mnli-xnli")
```


## Data-Wrangling

Next, we load the comment data.

```{python}
# loading comments data
data_path = "data/data_raw.csv"
d_raw = pd.read_csv(data_path)
```