project:
  type: website
  output-dir: docs

lang: en

website:
  title: "Like Dislike"
  bread-crumbs: false
  repo-url: https://github.com/XMtRa/like_dislike
  repo-actions: [edit, source, issue]
  #page-navigation: true
  #back-to-top-navigation: true
  page-footer: 
    center: "© 2026, The Authors" 
    right: "<img src='images/logo_uzh.png' height='30px'>"
    left: "<img src='images/logo_dept.png' height='50px'>"

  navbar:
    collapse: true
    left:
      - href: index.qmd
        text: "Home"
      - href: 01_manuscript_rev.qmd
        text: "Manuscript Revised"
      - href: 07_manuscript.rmd
        text: "First Submission"
      - href: 08_preregistration_changes.rmd
        text: "Preregistration"

    tools:
      - icon: bluesky
        href: https://bsky.app/ # profile/tobiasdienlin.com
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/XMtRa/like_dislike

  sidebar:
    - title: "Home"
      style: "floating"
      search: true
      
      contents:
        - section: "Overview"
          contents:
            - index.qmd
        - section: "Website"
          contents:
            - 00_website.rmd
        - text: "---"

    - title: "Manuscript Revised"
      style: "floating"
      search: true
      contents:
        - section: "Main Text"
          contents:
            - 01_manuscript_rev.qmd
        - text: "---"
        - section: "Appendix"
          contents:
            - 02_analyses.qmd
            - 03_items.rmd
            - 04_comment_classification.qmd
            - 05_analyses_additional.qmd
            #- 06_analyses_revision.qmd


format:
  html:
    embed-resources: true
    theme:
      light: cosmo
      dark: cyborg
    css: styles.css
    toc: true
    toggle: true

    grid:
      margin-width: 300px
      body-width: 800px
      gutter-width: 100px
      
knitr:
  opts_chunk:
    fig.path: "assets/figures/"
    cache.path: "assets/cache/"